/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pa_17130854_proyecto_01;

import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author josea
 */
public class PA_17130854_Frame_01 extends javax.swing.JFrame {

    // Variables globales para el frame
    ArrayCuerpo cuerpos = new ArrayCuerpo();
    DefaultTableModel modelo;
    String [] nombres = {"A-", "B-", "C-", "D-", "E-", "F-", "G-", "H-"};
    

    ArrayCuerpo ejemplos = new ArrayCuerpo(3);

    public PA_17130854_Frame_01() {
        initComponents();
        // inicializar spinners
        jSpinnerEditar.setValue(1);
        jSpinnerNumElementos.setValue(0);
        jSpinnerUbicacionGrabar.setValue(1);

        // inicializar tabla
        jTableDatos.setShowGrid(true);
        modelo = (DefaultTableModel) jTableDatos.getModel();
        modelo.setRowCount(0);

        // inicializar ejemplos 
        ejemplos.setValueAt(0, "C-25", 288000000, 8090734385.12284);
        ejemplos.setValueAt(1, "M-18", 250000000, 651389761.823614);
        ejemplos.setValueAt(2, "A-87", 295000000, 504661558.46743);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jtfNombre = new javax.swing.JTextField();
        jtfVelocidad = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtfEnergia = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnCalcularMasa = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLResultadoMasa = new javax.swing.JLabel();
        btnGrabar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jSpinnerUbicacionGrabar = new javax.swing.JSpinner();
        btnEjemplo1 = new javax.swing.JButton();
        bntEjemplo2 = new javax.swing.JButton();
        btnEjemplo3 = new javax.swing.JButton();
        jCheckIncrementar = new javax.swing.JCheckBox();
        btnAleatorio = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jSpinnerNumElementos = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        jSpinnerEditar = new javax.swing.JSpinner();
        btnEditar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDatos = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        btnOrdenAlfabetico = new javax.swing.JButton();
        btnOrdenMasa = new javax.swing.JButton();
        btnOrdenVelocidad = new javax.swing.JButton();
        btnOrdenEnergia = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jComboBOrden = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        btnMayorMasa = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLMayorMasa = new javax.swing.JLabel();
        jLMenorMasa = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLSumaMasa = new javax.swing.JLabel();
        jLPromVelocidad = new javax.swing.JLabel();
        jLTotalEnergia = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Energia");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Energía relativista");

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel2.setText("Nombre: ");

        jLabel3.setText("Velocidad:");

        jLabel4.setText("Energia:");

        btnCalcularMasa.setText("Calcular masa");
        btnCalcularMasa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCalcularMasaMouseClicked(evt);
            }
        });

        jLabel5.setText("Resultado:");

        jLResultadoMasa.setBackground(new java.awt.Color(102, 255, 102));
        jLResultadoMasa.setText("0.0");
        jLResultadoMasa.setOpaque(true);

        btnGrabar.setText("Grabar");
        btnGrabar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGrabarMouseClicked(evt);
            }
        });

        jLabel8.setText("Ubicacion");

        jSpinnerUbicacionGrabar.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerUbicacionGrabarStateChanged(evt);
            }
        });

        btnEjemplo1.setText("Ejemplo 1");
        btnEjemplo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEjemplo1MouseClicked(evt);
            }
        });

        bntEjemplo2.setText("Ejemplo 2");
        bntEjemplo2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bntEjemplo2MouseClicked(evt);
            }
        });

        btnEjemplo3.setText("Ejemplo 3");
        btnEjemplo3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEjemplo3MouseClicked(evt);
            }
        });

        jCheckIncrementar.setText("Auto incrementar");

        btnAleatorio.setText("Aleatorio");
        btnAleatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAleatorioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfVelocidad, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnEjemplo1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bntEjemplo2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEjemplo3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jtfEnergia, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCalcularMasa)
                        .addGap(59, 59, 59))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLResultadoMasa, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpinnerUbicacionGrabar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnGrabar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAleatorio))
                    .addComponent(jCheckIncrementar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jtfVelocidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jtfEnergia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCalcularMasa)
                    .addComponent(jLabel8)
                    .addComponent(jSpinnerUbicacionGrabar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGrabar)
                    .addComponent(btnAleatorio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLResultadoMasa, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnEjemplo1)
                        .addComponent(bntEjemplo2)
                        .addComponent(btnEjemplo3))
                    .addComponent(jCheckIncrementar)))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel6.setText("Número de elementos: ");

        jSpinnerNumElementos.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerNumElementosStateChanged(evt);
            }
        });

        jLabel7.setText("Edicion en: ");

        jSpinnerEditar.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerEditarStateChanged(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditarMouseClicked(evt);
            }
        });

        jTableDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Masa (Kg)", "Velocidad (m/s)", "Energía Relativista(Nw)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableDatos);

        jLabel9.setText("Suma / Promedio:");

        jLabel10.setText("Ordenamiento por: ");

        btnOrdenAlfabetico.setText("Alfabético");
        btnOrdenAlfabetico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdenAlfabeticoActionPerformed(evt);
            }
        });

        btnOrdenMasa.setText("Masa");
        btnOrdenMasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdenMasaActionPerformed(evt);
            }
        });

        btnOrdenVelocidad.setText("Velocidad");
        btnOrdenVelocidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdenVelocidadActionPerformed(evt);
            }
        });

        btnOrdenEnergia.setText("Energía");
        btnOrdenEnergia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdenEnergiaActionPerformed(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pa_17130854_proyecto_01/Captura.jpg"))); // NOI18N

        jComboBOrden.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Descendente\t", "Ascendete" }));

        jButton1.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jButton1.setText("Información del proyecto");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(135, Short.MAX_VALUE))
        );

        btnMayorMasa.setText("Mayor");
        btnMayorMasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMayorMasaActionPerformed(evt);
            }
        });

        jButton3.setText("Menor");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLMayorMasa.setBackground(new java.awt.Color(255, 204, 204));
        jLMayorMasa.setOpaque(true);

        jLMenorMasa.setBackground(new java.awt.Color(255, 204, 204));
        jLMenorMasa.setOpaque(true);

        jLabel14.setText("Mayor/menor masa:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel10)
                            .addComponent(btnOrdenAlfabetico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnOrdenMasa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnOrdenEnergia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnOrdenVelocidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBOrden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(124, 124, 124)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jButton3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLMenorMasa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel14)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(btnMayorMasa)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLMayorMasa, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jComboBOrden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOrdenAlfabetico)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOrdenMasa)
                    .addComponent(btnMayorMasa)
                    .addComponent(jLMayorMasa, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOrdenVelocidad)
                    .addComponent(jButton3)
                    .addComponent(jLMenorMasa, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOrdenEnergia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jLSumaMasa.setBackground(new java.awt.Color(153, 255, 255));
        jLSumaMasa.setOpaque(true);

        jLPromVelocidad.setBackground(new java.awt.Color(153, 255, 255));
        jLPromVelocidad.setOpaque(true);

        jLTotalEnergia.setBackground(new java.awt.Color(153, 255, 255));
        jLTotalEnergia.setOpaque(true);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpinnerNumElementos, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(150, 150, 150)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpinnerEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLSumaMasa, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLPromVelocidad, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLTotalEnergia, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jSpinnerNumElementos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jSpinnerEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEditar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLSumaMasa, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLPromVelocidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLTotalEnergia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(372, 372, 372)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /* 
        Disparadores de eventos de los controles del frame
     */
    // Botón calcular masa, evento click
    private void btnCalcularMasaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCalcularMasaMouseClicked

        // leer datos de los text fields
        Cuerpo c = leerDatos();

        jLResultadoMasa.setText(
                String.format("%.9f", c.calcularMasa()
                )
        );
    }//GEN-LAST:event_btnCalcularMasaMouseClicked


    private void jSpinnerUbicacionGrabarStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerUbicacionGrabarStateChanged
        if ((int) jSpinnerUbicacionGrabar.getValue() < 1) {
            jSpinnerUbicacionGrabar.setValue(1);
        }
    }//GEN-LAST:event_jSpinnerUbicacionGrabarStateChanged

    // cambio de numero de elementos, evitar numeros negativos
    private void jSpinnerNumElementosStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerNumElementosStateChanged
        if ((int) jSpinnerNumElementos.getValue() < 0) {
            jSpinnerNumElementos.setValue(0);
        } else {
            int tamaño = (int) jSpinnerNumElementos.getValue();
            cuerpos.cambiarTamaño(tamaño);
            modelo.setRowCount(0);
            modelo.setRowCount(tamaño);
            mostrar();
        }
    }//GEN-LAST:event_jSpinnerNumElementosStateChanged

    private void jSpinnerEditarStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerEditarStateChanged
        if ((int) jSpinnerEditar.getValue() < 1) {
            jSpinnerEditar.setValue(1);
        }
    }//GEN-LAST:event_jSpinnerEditarStateChanged

    private void btnEjemplo1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEjemplo1MouseClicked
        ejemplo(0);
    }//GEN-LAST:event_btnEjemplo1MouseClicked

    private void bntEjemplo2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntEjemplo2MouseClicked
        ejemplo(1);
    }//GEN-LAST:event_bntEjemplo2MouseClicked

    private void btnEjemplo3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEjemplo3MouseClicked
        ejemplo(2);
    }//GEN-LAST:event_btnEjemplo3MouseClicked

    private void btnGrabarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGrabarMouseClicked

        // leer datos de los text fields
        Cuerpo cuerpo = leerDatos();
        int posicion = (int) jSpinnerUbicacionGrabar.getValue() - 1;
        if (posicion < cuerpos.getTamaño()) {
            cuerpos.setCuerpoAt(posicion, cuerpo);
            if (jCheckIncrementar.isSelected()) {
                jSpinnerUbicacionGrabar.setValue(posicion + 2);
            }
        }
        mostrar();
    }//GEN-LAST:event_btnGrabarMouseClicked

    private void btnEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarMouseClicked
        putDatos();
    }//GEN-LAST:event_btnEditarMouseClicked

    private void btnOrdenAlfabeticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdenAlfabeticoActionPerformed
        if (jComboBOrden.getSelectedIndex() == 0) {
            cuerpos.ordenarAlfabetico();
        }else if(jComboBOrden.getSelectedIndex() == 1){
            cuerpos.ordenarAlfabeticoDesc();
        }
        mostrar();
    }//GEN-LAST:event_btnOrdenAlfabeticoActionPerformed

    private void btnOrdenMasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdenMasaActionPerformed
        if (jComboBOrden.getSelectedIndex() == 0) {
            cuerpos.ordenarMasa();
        }else if ( jComboBOrden.getSelectedIndex() == 1) {
            cuerpos.ordenarMasaDesc();
        }
        mostrar();
    }//GEN-LAST:event_btnOrdenMasaActionPerformed

    private void btnOrdenVelocidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdenVelocidadActionPerformed
        if (jComboBOrden.getSelectedIndex() == 0) {
            cuerpos.ordenVelocidad();
        }else if ( jComboBOrden.getSelectedIndex() == 1) {
            cuerpos.ordenVelocidadDesc();
        }
        mostrar();
    }//GEN-LAST:event_btnOrdenVelocidadActionPerformed

    private void btnOrdenEnergiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdenEnergiaActionPerformed
        if (jComboBOrden.getSelectedIndex() == 0) {
            cuerpos.ordenEnergia();
        }else if ( jComboBOrden.getSelectedIndex() == 1) {
            cuerpos.ordenEnergiaDesc();
        }
        mostrar();
    }//GEN-LAST:event_btnOrdenEnergiaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // mandar mensaje con datos del proyecto
        String str = "Nombre: José Antonio Zandate Luna\n"
                + "No. Control: 17130854\n"
                + "No. Proyecto: 1\n"
                + "Descripción: Programa que calcula la masa de un cuerpo segun su velocidad y su energia relativista\n";
        JOptionPane.showMessageDialog(null, str);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnAleatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAleatorioActionPerformed
        // TODO add your handling code here:
        Random r = new Random();
        jtfNombre.setText(nombres[r.nextInt(nombres.length)] + r.nextInt(10));
        jtfVelocidad.setText(""+r.nextInt(10000)*10000);
        jtfEnergia.setText(""+r.nextInt(10000)*100000);
    }//GEN-LAST:event_btnAleatorioActionPerformed

    private void btnMayorMasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMayorMasaActionPerformed
        // TODO add your handling code here:
        jLMayorMasa.setText(cuerpos.mayorMasa().getNombre());
    }//GEN-LAST:event_btnMayorMasaActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jLMenorMasa.setText(cuerpos.menorMasa().getNombre());
    }//GEN-LAST:event_jButton3ActionPerformed

    // operaciones comunes en el frame
    private void mostrar() {
        double sumaMasa = 0, sumaVelocidad = 0, sumaEnergia = 0;

        if (cuerpos.isEmpty()) {
            return;
        }
        int n = 0;
        for (int r = 0; r < cuerpos.getTamaño(); r++) {
            Cuerpo c = cuerpos.getCuerpoAt(r);
            if (c != null) {
                n++;
                jTableDatos.setValueAt(c.getNombre(), r, 0);
                jTableDatos.setValueAt(String.format("%.9f", c.calcularMasa()), r, 1);
                jTableDatos.setValueAt(String.format("%f", c.getVelocidad()), r, 2);
                jTableDatos.setValueAt(String.format("%f", c.getEnergia()), r, 3);

                sumaMasa += c.calcularMasa();
                sumaVelocidad += c.getVelocidad();
                sumaEnergia += c.getEnergia();
            }
        }

        jLSumaMasa.setText("" + String.format("%.9f", sumaMasa));
        jLPromVelocidad.setText("" + (String.format("%f", (sumaVelocidad / n))));
        jLTotalEnergia.setText("" + String.format("%f", sumaEnergia));
    }

    private void ejemplo(int numero) {
        jtfNombre.setText(ejemplos.getCuerpoAt(numero).getNombre());
        jtfVelocidad.setText("" + ejemplos.getCuerpoAt(numero).getVelocidad());
        jtfEnergia.setText("" + ejemplos.getCuerpoAt(numero).getEnergia());
    }

    private Cuerpo leerDatos() {
        // obtener datos
        String nombre = jtfNombre.getText();
        double velocidad = Double.valueOf(jtfVelocidad.getText());
        double energia = Double.valueOf(jtfEnergia.getText());

        return new Cuerpo(nombre, velocidad, energia);
    }

    private void putDatos() {
        int posicion = (int) jSpinnerEditar.getValue() - 1;
        jSpinnerUbicacionGrabar.setValue(posicion + 1);

        // salir si no existe el dato en la posicion
        if (cuerpos.getCuerpoAt(posicion) == null) {
            return;
        }

        Cuerpo datos = cuerpos.getCuerpoAt(posicion);
        jCheckIncrementar.setSelected(false);

        jtfNombre.setText(datos.getNombre());
        jtfVelocidad.setText("" + datos.getVelocidad());
        jtfEnergia.setText("" + datos.getEnergia());
    }

    public static void main(String args[]) {


        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PA_17130854_Frame_01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PA_17130854_Frame_01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PA_17130854_Frame_01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PA_17130854_Frame_01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PA_17130854_Frame_01().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntEjemplo2;
    private javax.swing.JButton btnAleatorio;
    private javax.swing.JButton btnCalcularMasa;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEjemplo1;
    private javax.swing.JButton btnEjemplo3;
    private javax.swing.JButton btnGrabar;
    private javax.swing.JButton btnMayorMasa;
    private javax.swing.JButton btnOrdenAlfabetico;
    private javax.swing.JButton btnOrdenEnergia;
    private javax.swing.JButton btnOrdenMasa;
    private javax.swing.JButton btnOrdenVelocidad;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckIncrementar;
    private javax.swing.JComboBox<String> jComboBOrden;
    private javax.swing.JLabel jLMayorMasa;
    private javax.swing.JLabel jLMenorMasa;
    private javax.swing.JLabel jLPromVelocidad;
    private javax.swing.JLabel jLResultadoMasa;
    private javax.swing.JLabel jLSumaMasa;
    private javax.swing.JLabel jLTotalEnergia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinnerEditar;
    private javax.swing.JSpinner jSpinnerNumElementos;
    private javax.swing.JSpinner jSpinnerUbicacionGrabar;
    private javax.swing.JTable jTableDatos;
    private javax.swing.JTextField jtfEnergia;
    private javax.swing.JTextField jtfNombre;
    private javax.swing.JTextField jtfVelocidad;
    // End of variables declaration//GEN-END:variables
}
